### PR TITLE
Create Listener class

### PR DESCRIPTION
**Pull request by nina-dk**
I created a `Listener` class with `click` and `pressEnter` instance methods that can handle multiple callbacks.

### CODE REVIEW

**Review by medic-code — COMMENTED** [review]
Nice changes to reduce the amount of method invocations! 

I wonder whether we need to check if the number of callbacks are less than 2 ? Could we not just loop around the number of callbacks and if that number is 1 then it executes and then if it's more than execute each callback in turn ?

**Comment by nina-dk** [comment]
You're right, @medic-code . Removed it 👍🏻

**Review by medic-code — APPROVED** [review]
Good job!

**Comment by eamon0989** [comment]
Nice one! Merged.

**Pull request merged**
